import sqlite3
c = sqlite3.connect("C:/Users/BrianChan/Documents/crypto_trading_bot/data/trading_bot.db")
print("--- trades by status/asset ---")
for r in c.execute("SELECT status, asset_type, COUNT(*) FROM trades GROUP BY status, asset_type"): print(r)
print("--- closed: asset, n, sumPnl, avgPnlPct, wins ---")
for r in c.execute("SELECT asset_type, COUNT(*), ROUND(SUM(realized_pnl),2), ROUND(AVG(realized_pnl_pct),3), SUM(CASE WHEN realized_pnl>0 THEN 1 ELSE 0 END) FROM trades WHERE status='closed' GROUP BY asset_type"): print(r)
print("--- signals by type/asset ---")
for r in c.execute("SELECT signal_type, asset_type, COUNT(*) FROM signals GROUP BY signal_type, asset_type"): print(r)
print("--- avg win vs avg loss (pct) ---")
for r in c.execute("SELECT CASE WHEN realized_pnl>0 THEN 'win' ELSE 'loss' END g, COUNT(*), ROUND(AVG(realized_pnl_pct),3) FROM trades WHERE status='closed' GROUP BY g"): print(r)
print("--- holding period (hours) ---")
for r in c.execute("SELECT ROUND(AVG((julianday(closed_at)-julianday(opened_at))*24),2) FROM trades WHERE status='closed' AND closed_at IS NOT NULL"): print(r)
print("--- open positions ---")
for r in c.execute("SELECT symbol, asset_type, ROUND(entry_price,2), ROUND(position_size_usd,2) FROM trades WHERE status='open'"): print(r)
