"""SQLAlchemy models for the trading bot database."""

from datetime import datetime
from typing import Optional
from sqlalchemy import (
    Column, Integer, String, Float, DateTime, Boolean, Text, Enum as SQLEnum,
    ForeignKey, Index, create_engine
)
from sqlalchemy.orm import declarative_base, relationship
import enum

Base = declarative_base()


class TradeStatus(enum.Enum):
    """Trade status enumeration."""
    PENDING = "pending"
    OPEN = "open"
    CLOSED = "closed"
    CANCELLED = "cancelled"


class TradeType(enum.Enum):
    """Trade type enumeration."""
    BUY = "buy"
    SELL = "sell"


class SignalType(enum.Enum):
    """Signal type enumeration."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class SentimentSource(enum.Enum):
    """Sentiment data source enumeration."""
    REDDIT = "reddit"
    TWITTER = "twitter"
    NEWS = "news"


class MarketData(Base):
    """OHLCV market data model."""
    __tablename__ = "market_data"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(10), nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, nullable=False)
    timeframe = Column(String(10), default="1h")  # 1m, 5m, 15m, 1h, 4h, 1d

    __table_args__ = (
        Index("ix_market_data_symbol_timestamp", "symbol", "timestamp"),
    )

    def __repr__(self):
        return f"<MarketData({self.symbol}, {self.timestamp}, close={self.close})>"


class SentimentData(Base):
    """Sentiment data from various sources."""
    __tablename__ = "sentiment_data"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(10), nullable=False, index=True)
    source = Column(SQLEnum(SentimentSource), nullable=False)
    timestamp = Column(DateTime, nullable=False, index=True)
    score = Column(Float, nullable=False)  # -1 to 1 scale
    magnitude = Column(Float, default=0.0)  # Confidence/strength
    text_sample = Column(Text, nullable=True)  # Sample text for reference
    post_count = Column(Integer, default=1)  # Number of posts aggregated
    extra_data = Column(Text, nullable=True)  # JSON metadata

    __table_args__ = (
        Index("ix_sentiment_symbol_source_timestamp", "symbol", "source", "timestamp"),
    )

    def __repr__(self):
        return f"<SentimentData({self.symbol}, {self.source.value}, score={self.score})>"


class TechnicalIndicator(Base):
    """Calculated technical indicators."""
    __tablename__ = "technical_indicators"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(10), nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)

    # RSI
    rsi = Column(Float, nullable=True)

    # MACD
    macd = Column(Float, nullable=True)
    macd_signal = Column(Float, nullable=True)
    macd_histogram = Column(Float, nullable=True)

    # Bollinger Bands
    bb_upper = Column(Float, nullable=True)
    bb_middle = Column(Float, nullable=True)
    bb_lower = Column(Float, nullable=True)

    # EMAs
    ema_20 = Column(Float, nullable=True)
    ema_50 = Column(Float, nullable=True)
    ema_200 = Column(Float, nullable=True)

    # ATR (for stop-loss calculation)
    atr = Column(Float, nullable=True)

    # Volume indicators
    volume_sma = Column(Float, nullable=True)
    volume_ratio = Column(Float, nullable=True)  # Current volume / SMA

    __table_args__ = (
        Index("ix_technical_symbol_timestamp", "symbol", "timestamp"),
    )

    def __repr__(self):
        return f"<TechnicalIndicator({self.symbol}, {self.timestamp})>"


class Signal(Base):
    """Trading signals generated by the strategy."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(10), nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow, index=True)
    signal_type = Column(SQLEnum(SignalType), nullable=False)

    # Scores
    technical_score = Column(Float, nullable=False)
    sentiment_score = Column(Float, nullable=False)
    combined_score = Column(Float, nullable=False)

    # Signal details
    strength = Column(Float, default=0.0)  # 0-1 scale
    confidence = Column(Float, default=0.0)  # 0-1 scale

    # Recommended trade parameters
    entry_price = Column(Float, nullable=True)
    stop_loss = Column(Float, nullable=True)
    take_profit = Column(Float, nullable=True)
    position_size_pct = Column(Float, nullable=True)

    # Execution status
    executed = Column(Boolean, default=False)
    trade_id = Column(Integer, ForeignKey("trades.id"), nullable=True)

    # Reasoning
    reasoning = Column(Text, nullable=True)  # JSON with detailed reasoning

    # Asset classification
    asset_type = Column(String(10), nullable=False, default="crypto")  # "crypto" | "stock"

    trade = relationship("Trade", back_populates="signal")

    def __repr__(self):
        return f"<Signal({self.symbol}, {self.signal_type.value}, score={self.combined_score})>"


class Trade(Base):
    """Trade records."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(10), nullable=False, index=True)
    trade_type = Column(SQLEnum(TradeType), nullable=False)
    status = Column(SQLEnum(TradeStatus), nullable=False, default=TradeStatus.PENDING)

    # Timestamps
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    opened_at = Column(DateTime, nullable=True)
    closed_at = Column(DateTime, nullable=True)

    # Order details
    entry_price = Column(Float, nullable=True)
    exit_price = Column(Float, nullable=True)
    quantity = Column(Float, nullable=False)
    position_size_usd = Column(Float, nullable=False)

    # Risk management
    stop_loss = Column(Float, nullable=True)
    take_profit = Column(Float, nullable=True)

    # Results
    realized_pnl = Column(Float, nullable=True)
    realized_pnl_pct = Column(Float, nullable=True)
    fees = Column(Float, default=0.0)

    # Order IDs (for live trading)
    entry_order_id = Column(String(100), nullable=True)
    exit_order_id = Column(String(100), nullable=True)

    # Paper trading flag
    is_paper = Column(Boolean, default=True)

    # Asset classification
    asset_type = Column(String(10), nullable=False, default="crypto")  # "crypto" | "stock"

    # Notes
    notes = Column(Text, nullable=True)

    signal = relationship("Signal", back_populates="trade", uselist=False)

    def __repr__(self):
        return f"<Trade({self.id}, {self.symbol}, {self.trade_type.value}, {self.status.value})>"

    @property
    def is_open(self) -> bool:
        return self.status == TradeStatus.OPEN

    def calculate_pnl(self, current_price: float) -> float:
        """Calculate unrealized P&L at current price."""
        if not self.entry_price or not self.quantity:
            return 0.0

        if self.trade_type == TradeType.BUY:
            return (current_price - self.entry_price) * self.quantity
        else:  # SELL (short)
            return (self.entry_price - current_price) * self.quantity


class Portfolio(Base):
    """Portfolio state tracking."""
    __tablename__ = "portfolio"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow, index=True)

    # Balances
    total_value_usd = Column(Float, nullable=False)
    cash_balance_usd = Column(Float, nullable=False)
    positions_value_usd = Column(Float, nullable=False)

    # Performance metrics
    daily_pnl = Column(Float, default=0.0)
    daily_pnl_pct = Column(Float, default=0.0)
    total_pnl = Column(Float, default=0.0)
    total_pnl_pct = Column(Float, default=0.0)

    # Risk metrics
    open_positions_count = Column(Integer, default=0)
    max_drawdown = Column(Float, default=0.0)

    # Paper trading flag
    is_paper = Column(Boolean, default=True)

    def __repr__(self):
        return f"<Portfolio({self.timestamp}, value={self.total_value_usd})>"


class PerformanceMetrics(Base):
    """Trading performance metrics."""
    __tablename__ = "performance_metrics"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow, index=True)
    period = Column(String(20), nullable=False)  # daily, weekly, monthly, all_time

    # Trade statistics
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)
    win_rate = Column(Float, default=0.0)

    # P&L metrics
    total_pnl = Column(Float, default=0.0)
    average_win = Column(Float, default=0.0)
    average_loss = Column(Float, default=0.0)
    profit_factor = Column(Float, default=0.0)

    # Risk metrics
    max_drawdown = Column(Float, default=0.0)
    sharpe_ratio = Column(Float, nullable=True)
    sortino_ratio = Column(Float, nullable=True)

    # Paper trading flag
    is_paper = Column(Boolean, default=True)

    def __repr__(self):
        return f"<PerformanceMetrics({self.period}, win_rate={self.win_rate})>"
